### ISSUE TITLE
Gather statistics on mysqld_exporter collection performance

### ISSUE THREAD

**Issue by grypyrg** [prometheus/mysqld_exporter#188]
It would be helpful if we also send data back to prometheus with the time it took to run each of the collectors. 

Some of the exporter functionality does some extensive queries, and might even get stuck, rung long time in various cases (when there are a lot of tables, when there are metadatalocks...).

That way we can easily troubleshoot, pinpoint what query/part caused the scrape duration to be so high.

**Comment by SuperQ** [comment]
Seems like a good idea to me.

**Comment by mkuratczyk** [comment]
Hi. I had the same need (scrape took 2 minutes for us) so I added duration for each collector. You can see that here: https://github.com/mkuratczyk/mysqld_exporter/commits/master. Would anyone have a moment to test and/or review it?
In our case it turned out that info_schema_tables collector took almost all that time so there is an additional metric to split that time by schema. We decided to just turn that collector off (collect.info_schema.tables=false) because it was not worth it to collect all those details so often.

**Comment by SuperQ** [comment]
Instead of implementing it in each collector, I would implement it in the main function with a per-collector label.  This could also be done as a histogram.

**Comment by brian-brazil** [comment]
This should be a per-scrape gauge, like it's in the node exporter.

**Comment by SuperQ** [comment]
https://github.com/prometheus/mysqld_exporter/pull/197
