### ISSUE TITLE
New feature: support for custom queries

### ISSUE THREAD

**Issue by AlekSi** [prometheus/mysqld_exporter#230]
Allow one to create metrics with specified labels from custom queries. Like [that one for PostgreSQL](https://github.com/wrouesnel/postgres_exporter/blob/master/queries.yaml) or like [another one](https://github.com/mc2soft/postgresql_exporter/blob/master/queries.yaml).

We may work on it you are interested.

**Comment by SuperQ** [comment]
That feature in the PostgreSQL exporter is an anti-pattern for normal exporters.  We do not want to support that in this exporter.  Custom queries are typically used for application metrics, which are better solved with a [SQL exporter](https://github.com/chop-dbhi/prometheus-sql).

If there are specific MySQL metrics not supported by this exporter, they should be properly integrated as a normal collector.

**Comment by AlekSi** [comment]
> We do not want to support that in this exporter.

Ok. Then this issue can be closed.

**Comment by arvenil** [comment]
Hi @SuperQ :)
Totally agree. Just a short comment why we need this. The intent of this is to give user (e.g. DBA) a tool for easy prototyping metrics he wants. We can later collect such config (if he sends it) and turn it into a proper collector, but without it we will never know what we are missing since not everyone knows go and is willing to write new collector.
We are developing this functionality for ourselves as a separate collector, so if by any chance you find such prototyping tool useful then let us know, we can make upstream PR.

**Comment by SuperQ** [comment]
@arvenil I would recommend using the [sql_exporter](https://github.com/free/sql_exporter) for prototyping, it has a nice yaml file syntax, which makes it very easy to generate and test new queries.
