### ISSUE TITLE
FR: support different intervals for different metrics collectors

### ISSUE THREAD

**Issue by santec** [prometheus/mysqld_exporter#234]
It would be very nice to be able to configure different intervals for different collectors. For example, running queries on information_schema once a minute an show global status every 2 seconds.

I hope this is possible.

**Comment by SuperQ** [comment]
The exporter has no knowledge of collection intervals, this is driven by the Prometheus server's scrape interval.

Selecting collectors via params is a feature we would like to have, but this is not currently implemented.  Previously it was not possible with the Prometheus client library, but we can now implement it with a custom handler and registry.

But I personally don't have time to implement this at the moment.

**Comment by siavashs** [comment]
I will look into this 🙂

**Comment by delgod** [comment]
JFI: implemented in [percona/mysqld_exporter/mysqld_exporter.go#L899-L925](https://github.com/percona/mysqld_exporter/blob/master/mysqld_exporter.go#L899-L925)

**Comment by SuperQ** [comment]
Ahh, the entertainment of implementing basic auth, without ssl.  It makes me cringe that people think that's ok.

**Comment by SuperQ** [comment]
@delgod There are a whole bunch of problems with that implementation.
* It creates separate subsystems for each metric.  This is generally a useless/bad idea as it will create duplicate metrics of the same data.
* It creates a limited set of 3 different static exporter modes rather than a more dynamic configuration with a URL parameter like `/metrics?collectors=global_status,global_values`.
