### ISSUE TITLE
Startup time too long

### ISSUE THREAD

**Issue by adkhare** [prometheus/mysqld_exporter#261]
We have a mysql db which has close to 3k databases with around 300 tables each db.

We have noted that during the startup of the mysqld_exporter, the process starts scanning all the metrics instead of scanning only during `/metrics` call. Due to this, we are seeing close to 2 hours of start up time.

Please note that we know that disabling collection of `info_schema.table` will solve this. However, we need that info to be gathered.

is there any flag to disable this behaviour or open for a discussion on the approach?

Thanks
Amit Khare

**Comment by SuperQ** [comment]
I don't know what gives you the impression that this is happening, but there is no warmup in the exporter code.  Metrics gathering only happens on request.

What version of the `mysqld_exporter` are you using?

**Comment by adkhare** [comment]
we are using 0.10

**Comment by UmanShahzad** [comment]
Similar issue here:

```
Jun 11 16:16:13 <host> mysqld_exporter[21104]: time="2018-06-11T16:16:13Z" level=info msg="Starting mysqld_exporter (version=0.10.0, branch=master, revision=80680068f15474f87847c8ee8f18a2939a26196a)" source="mysqld_exporter.go:460"
Jun 11 16:16:13 <host> mysqld_exporter[21104]: time="2018-06-11T16:16:13Z" level=info msg="Build context (go=go1.8.1, user=<>@<>, date=20170425-11:24:12)" source="mysqld_exporter.go:461"
Jun 11 16:59:43 <host> mysqld_exporter[21104]: time="2018-06-11T16:59:43Z" level=info msg="Listening on 127.0.0.1:9104" source="mysqld_exporter.go:479"
```

See timestamps.

**Comment by UmanShahzad** [comment]
@adkhare @SuperQ After trying some things, it seems the issue is with `information_schema.tables` collector. I get instant startup and response times when using `-collect.info_schema.tables=false`. Using `-collect.info_schema.tables.databases` to specify only a single database (out of the 8000+ that we've got), time-to-listen was still a few seconds, and a call to `/metrics` took a few seconds as well, but it didn't timeout or anything like that.

**Comment by SuperQ** [comment]
Please re-test this with the latest 0.11.0 release. We made a number of improvements to the way the code starts and runs.

**Comment by UmanShahzad** [comment]
Good to hear, I'll test it out soon.

**Comment by UmanShahzad** [comment]
@SuperQ OK, that seems to fix the issue of the startup time being too long. It still takes forever to actually scrape metrics with `--collect.info_schema.tables` when there are too many databases, but I think that's a MySQL-level thing and not any fault of the exporter.

Since this issue is about startup time though, I think it's good to close.

**Comment by SuperQ** [comment]
Yes, there's nothing we can do about MySQL servers with very large schemas. I filed https://github.com/prometheus/mysqld_exporter/issues/299 to make it possible to use regexp filtering, but it's probably not going to help much for very large numbers of schemas.
