### ISSUE TITLE
Galera wsrep_evs_repl_latency not supported

### ISSUE THREAD

**Issue by chrsch** [prometheus/mysqld_exporter#309]
It would be really nice if the latency of the replication within the cluster was supported by reading from Galera variable wsrep_evs_repl_latency (http://galeracluster.com/documentation-webpages/galerastatusvariables.html#wsrep-evs-repl-latency)

**Comment by SuperQ** [comment]
Seems like a good feature.

/cc @rtreffer

**Comment by rtreffer** [comment]
Interesting, and useful.

**Comment by SuperQ** [comment]
@chrsch Care to make an attempt at adding a parser for this? It would involve adding the variable to the [textItems handler](https://github.com/prometheus/mysqld_exporter/blob/master/collector/global_status.go#L85-L89) and then adding an [additional handler](https://github.com/prometheus/mysqld_exporter/blob/master/collector/global_status.go#L144).

The one cleanup thing I would like would be to convert the `if` to a `switch`, since we're likely to add more special case handlers in the future.

I would also make parsing the text a separate function.

**Comment by chrsch** [comment]
I'll try to show up with a PR thanks for the pointers
