### ISSUE TITLE
Will an exporter collect data from several mysqld instance?

### ISSUE THREAD

**Issue by clearlylin** [prometheus/mysqld_exporter#324]
Use cgroup for resource isolation. The physical machines can run several mysql instances. Currently, multiple exporters need to be started for data collection, and whether an exporter instance can be used to collect data of multiple instances.

**Comment by SuperQ** [comment]
No, exporters are designed to be running 1:1 with their targets. This allows Prometheus to identify which metrics belong to which target. There are no target labels on Prometheus metrics by design.

For usage questions/help, please use our [community](https://prometheus.io/community/). On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by clearlylin** [comment]
Thanks.
1:1 is not suitable for cloud environment，exporters management becomes complicated.
