### ISSUE TITLE
Invalid metric names are still included with MySql 8.0.12 after #307 was fixed.

### ISSUE THREAD

**Issue by yamac** [prometheus/mysqld_exporter#325]
### Host operating system: output of `uname -a`
Linux d001 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### mysqld_exporter version: output of `mysqld_exporter --version`
mysqld_exporter, version 0.11.0 (branch: master, revision: c8e3120d1fd0296d0fc6c9bb0997a53446fbdc8c)
build date:       20180901-11:42:45
go version:       go1.9.4

### MySQL server version
8.0.12

### mysqld_exporter command line flags
DATA_SOURCE_NAME="username:password@(localhost:3306)/" ./mysqld_exporter

### What did you do that produced an error?
Run the exporter with MySQL 8.0.12.

### What did you expect to see?
Works correctly.

### What did you see instead?
curl -s http://localhost:9104/metrics | promtool check metrics
error while linting: text format parsing error in line 896: invalid metric name in comment

#### L896-L898 of metrics.
```
# HELP mysql_global_status_validate_password.dictionary_file_words_count Generic metric from SHOW GLOBAL STATUS.
# TYPE mysql_global_status_validate_password.dictionary_file_words_count untyped
mysql_global_status_validate_password.dictionary_file_words_count 0
```

It seems that the #307 still remains.
`mysql_global_status_validate_password.dictionary_file_words_count` is not a valid metric name.

#### I found a location of this problem.
I have replaced `strings.ToLower` with `validPrometheusName` to fix then works fine for me.
```
--- collector/global_status.go  2018-09-01 20:41:51.433231551 +0900
+++ collectors/global_status.go.fixed      2018-09-01 20:41:47.593249719 +0900
@@ -5,7 +5,6 @@
 import (
        "database/sql"
        "regexp"
-       "strings"

        "github.com/prometheus/client_golang/prometheus"
 )
@@ -93,7 +92,7 @@
                        return err
                }
                if floatVal, ok := parseStatus(val); ok { // Unparsable values are silently skipped.
-                       key = strings.ToLower(key)
+                       key = validPrometheusName(key)
                        match := globalStatusRE.FindStringSubmatch(key)
                        if match == nil {
                                ch <- prometheus.MustNewConstMetric(
```

I don't know that this issue started with MySql 8.0.12 or not.

**Comment by Juniorpqp** [comment]
Hello,
I have problem same to describe:
Linux CENTOS 7 
=====
mysqld_exporter
invalid metric type "dictionary_file_words_count untyped" 
=====
SERVICE = OK

[root@mysql-dev ~]# systemctl status mysqld_exporter
● mysqld_exporter.service - Prometheus MySQL Exporter
   Loaded: loaded (/usr/lib/systemd/system/mysqld_exporter.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-10-03 11:26:07 NZDT; 11min ago
 Main PID: 13658 (mysqld_exporter)
   CGroup: /system.slice/mysqld_exporter.service
           └─13658 /usr/bin/mysqld_exporter --config.my-cnf /etc/.mysqld_exporter.cnf --collect.global_status --collect.info_schema.innodb_metrics --collect.auto_increment.columns --collect.info_schema.processlist --collect.binlog_siz...

Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.perf_schema.eventswaits" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.perf_schema.file_events" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.binlog_size" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.perf_schema.tableiowaits" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.perf_schema.indexiowaits" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.perf_schema.tablelocks" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.info_schema.query_response_time" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.info_schema.userstats" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg=" --collect.info_schema.tablestats" source="mysqld_exporter.go:222"
Oct 03 11:26:07 mysql-dev mysqld_exporter[13658]: time="2018-10-03T11:26:07+13:00" level=info msg="Listening on :9104" source="mysqld_exporter.go:232"
============

But, what file I need to change? I don't locate.
Thanks
Junior

**Comment by Juniorpqp** [comment]
Good morning.

I didn`t find the solution on the Internet and here too, but I fix this problem.

This problem apparently caused to pluggin:
mysql> SHOW VARIABLES LIKE '%dictionary%';
+-----------------------------------+-------+
| Variable_name                     | Value |
+-----------------------------------+-------+
| validate_password.dictionary_file |       |
+-----------------------------------+-------+
1 row in set (0.00 sec)

**To resolve this problem, I disabled in the mysql:**

mysql> SELECT @@plugin_dir;
+--------------------------+
| @@plugin_dir             |
+--------------------------+
| /usr/lib64/mysql/plugin/ |
+--------------------------+
1 row in set (0.00 sec)

mysql> UNINSTALL COMPONENT 'file://component_validate_password';

Restart mysql and the mysqld_export connect to Prometheus.

Thanks
Junior
