### ISSUE TITLE
Include individual index IO stats

### ISSUE THREAD

**Issue by SuperQ** [prometheus/mysqld_exporter#96]
It turns out it's incorrect to ignore stats from indexes that are not the "NULL" stat in `collect.perf_schema.indexiowaits`.  There are per-index io stats that are probably useful to see where the database is spending it's time updating individual indexes.

We need to re-evaluate which index stats are included.

**Comment by SuperQ** [comment]
@PeterZaitsev I did some checking, and I can find no cases where `performance_schema.table_io_waits_summary_by_index_usage.COUNT_INSERT` was non-zero outside of the NULL index name.  I found some use of `COUNT_UPDATE` and `COUNT_DELETE`.

Can you confirm this behavior?

**Comment by SuperQ** [comment]
Fixed

**Comment by PeterZaitsev** [comment]
Hi Ben,

Sorry I did not "confirm" it in time. Really I do not check.  In reality there is cost maintaining indexes for IO operations so it  might be bug or not implemented yet.  I know you do not like metrics which appear and dissapear but I think better approach in cases like this to capture stuff which has been non zero (since uptime)  as if the metric is implemented enabled and make sense for given workload it is likely not to have zero value.

**Comment by SuperQ** [comment]
The new version captures everything but INSERT metrics, for now this should be sufficient.  We can always revisit this in the future.

Also, we're working on a new compression method that reduces the overhead for collecting zeros to sub 1 byte per sample. :-)
